services:
  3cx-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024m
