services:
  3cx-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    env_file:
      - .env
    volumes:
      - ./screenshots:/app/screenshots
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048m
